// Copyright (c) 2023 Input Output (IOG).
// Copyright (c) 2026 Sakura Industries LLC.
//
// SPDX-License-Identifier: MIT OR Apache-2.0

// cspell: words CTLOP aname groupsocket typesocket RANGEOP tstr

#![allow(dead_code)] // TODO: find a way to remove this.

pub(crate) const CTLOP_PASSES: &[&str] = &[
    ".size",
    ".bits",
    ".regexp",
    ".cbor",
    ".cborseq",
    ".within",
    ".and",
    ".lt",
    ".le",
    ".gt",
    ".ge",
    ".eq",
    ".ne",
    ".default",
    ".x-enc",
    ".x-hash",
    ".x-compressed",
    ".x-brotli",
    ".x-zstd",
    ".x-gzip",
    ".x-deflate",
    ".x-enc.abnf",
    ".x-enc.abnfb",
    ".x-hash.abnf",
    ".x-hash.abnfb",
    ".x-compressed.abnf",
    ".x-compressed.abnfb",
    ".x-brotli.abnf",
    ".x-brotli.abnfb",
    ".x-zstd.abnf",
    ".x-zstd.abnfb",
    ".x-gzip.abnf",
    ".x-gzip.abnfb",
    ".x-deflate.abnf",
    ".x-deflate.abnfb",
    ".plus",
    ".cat",
    ".det",
    ".abnf",
    ".abnfb",
    ".feature",
    ".b64u",
    ".b64u-sloppy",
    ".b64c",
    ".b64c-sloppy",
    ".b45",
    ".b32",
    ".h32",
    ".hex",
    ".hexlc",
    ".hexuc",
    ".base10",
    ".printf",
    ".json",
    ".join",
    ".sdnv",
    ".sdnvseq",
    ".oid",
    ".prefp",
    ".prefpseq",
    ".dtrm",
    ".dtrmseq",
];

pub(crate) const CTLOP_FAILS: &[&str] = &[
    "aname.",
    ".",
    "..",
    "aname-",
    "aname%",
    "a%name4",
    "a^name5",
    "a name",
    "",
    // Wildcard identifiers no longer accepted:
    ".$",
    ".@",
    "._",
    ".a",
    ".z",
    ".A",
    ".Z",
    ".$$",
    ".@@",
    ".__",
    ".a$",
    ".a@",
    ".a_",
    ".$0",
    ".@9",
    "._a",
    ".abc",
    ".aname",
    ".@aname",
    "._aname",
    ".$aname",
    ".a$name",
    ".a.name",
    ".@a.name",
    ".$a.name",
    "._a.name",
    ".$$",
    ".$$groupsocket",
    ".$",
    ".$typesocket",
    // Rejected wildcard ctlops that were previously passes:
    ".something",
    ".not-an-operator",
    ".x",
    ".foo",
    ".bar",
    ".baz",
    ".myctl",
];

pub(crate) const RANGEOP_PASSES: &[&str] = &["..", "..."];

pub(crate) const RANGEOP_FAILS: &[&str] = &[".", "", "....", ".. .", ". .."];

pub(crate) const TYPE2_PASSES: &[&str] = &[
    "#",
    "#1",
    "#1.1",
    "#1.1",
    "#6",
    "#6.11",
    "#6.11(tstr)",
    "#6.11(\tstr\n)",
    "#6.<11>(tstr)",
    "#6.<TAG_FOR_THIS_SEMANTICS>(scope)",
    "#6.<1668546817..1668612095>(content)",
    "#6.11({ foo })",
    "#6.11([ foo ])",
    "#6.11(#3.1)",
    "#7",
    "#7.25",
    "#7.<25>",
    "#7.<1..23>",
    "&foo",
    "& foo<bar>",
    "&((+ a) // (b / c))",
    "&\t( foo: bar )",
    "~foo",
    "~ foo<bar>",
    "foo<bar>",
    "[ foo bar ]",
    "{ foo bar }",
    "(a)",
    "(a / b)",
    "(#)",
    "((a))",
    "1",
    "h'1111'",
    "true",
    "foo",
];

pub(crate) const TYPE2_FAILS: &[&str] = &[
    "",
    "##",
    "#1.",
    "#6.11 (tstr)",
    "#6.<11> (tstr)",
    "#6.<>(tstr)",
    "#7.<25>(tstr)",
    "#6.11(( foo: uint ))",
    "&",
    "& foo <bar>",
    "(foo bar)",
];

pub(crate) const TYPE1_PASSES: &[&str] = &[
    "1..2",
    "1 .. 2",
    "1\t..\n2",
    "1...2",
    "0..10.0", // BAD range 1
    "0.0..10", // BAD range 2
    "0..max-byte",
    "min-type..max-byte",
    "1.0..2.0",
    "1.0...2.0",
    "foo.size",
];

pub(crate) const TYPE1_FAILS: &[&str] = &[""];

pub(crate) const TYPE_PASSES: &[&str] = &[
    "1 / 2",
    "1\n/\t2",
    "1 / 2 / 3 / 4",
    "1 / (2 / (3 / 4))",
    "# / #",
];

pub(crate) const TYPE_FAILS: &[&str] = &["", "1 \\ 2", "1 // 2", "1 2", "1 / 2 3"];
