[package]
name = "cbork-utils"
version = "0.0.4"
edition.workspace = true
rust-version.workspace = true
license = "MIT OR Apache-2.0"
description = "Shared CBOR utility helpers used across the CBORK workspace."
readme = "README.md"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
exclude = ["moon.yml"]

[lints]
workspace = true

[dependencies]
half = "2"
minicbor = { version = "2", features = ["std", "half"] }

[dev-dependencies]
proptest = { version = "1.6.0", features = ["attr-macro"] }
