// Copyright (c) 2026 Sakura Industries LLC.
//
// SPDX-License-Identifier: AGPL-3.0-only

//! Build metadata and asset manifest for the `cbork` CLI.
//!
//! The asset manifest embeds a sorted list of skill-bundle files so the
//! installed or published `cbork` binary does not depend on the source
//! checkout of `.agents/skills/cddl/` at runtime.

use std::{
    env, fs,
    io::{self, Write},
    path::{Component, Path},
};

/// Build script entry point.
fn main() {
    build_info_build::build_script();
    if let Err(err) = generate_agent_skills_manifest() {
        // Surface a hard error so the build fails loudly if the asset
        // manifest is unreadable.
        eprintln!("cbork: failed to generate agent-skills manifest: {err}");
        std::process::exit(1);
    }
}

/// Generate `OUT_DIR/agent_skills_manifest.rs` from `assets/agent-skills/`.
fn generate_agent_skills_manifest() -> io::Result<()> {
    let assets_root = Path::new("assets/agent-skills");
    let out_dir = env::var("OUT_DIR")
        .map_err(|err| io::Error::new(io::ErrorKind::NotFound, format!("OUT_DIR: {err}")))?;
    let manifest_path = Path::new(&out_dir).join("agent_skills_manifest.rs");

    println!("cargo:rerun-if-changed={}", assets_root.display());

    let bundles: Vec<BundleData> = if assets_root.is_dir() {
        let mut entries = Vec::new();
        for entry in fs::read_dir(assets_root)? {
            let entry = entry?;
            let bundle_path = entry.path();
            let bundle_id = entry.file_name().to_string_lossy().into_owned();
            reject_traversal_in_path(&bundle_id)
                .map_err(|msg| io::Error::new(io::ErrorKind::InvalidInput, msg))?;

            let meta = fs::symlink_metadata(&bundle_path)?;
            if meta.file_type().is_symlink() {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    format!("bundle {bundle_id} must not be a symlink"),
                ));
            }
            if !meta.is_dir() {
                continue;
            }

            let mut files = Vec::new();
            collect_files(&bundle_path, &bundle_path, &mut files)?;
            files.sort();

            entries.push(BundleData {
                id: bundle_id,
                files,
            });
        }
        entries.sort_by(|a, b| a.id.cmp(&b.id));
        entries
    } else {
        Vec::new()
    };

    for bundle in &bundles {
        for (rel, _) in &bundle.files {
            println!("cargo:rerun-if-changed={}/{}", assets_root.display(), rel);
        }
    }

    write_manifest(&manifest_path, &bundles)
}

/// In-memory description of one discovered bundle directory.
struct BundleData {
    /// Directory name used as the bundle identifier.
    id: String,
    /// Each entry: `(relative_path, bytes)` in the bundle's directory.
    files: Vec<(String, Vec<u8>)>,
}

/// Write the compiled `agent_skills_manifest.rs` into `OUT_DIR`.
fn write_manifest(
    manifest_path: &Path,
    bundles: &[BundleData],
) -> io::Result<()> {
    let mut file = fs::File::create(manifest_path)?;

    writeln!(file, "// Code generated by build.rs - DO NOT EDIT.")?;
    writeln!(file)?;

    writeln!(
        file,
        "/// A single file embedded into the binary as part of a skill bundle."
    )?;
    writeln!(file, "#[derive(Debug, Clone, Copy)]")?;
    writeln!(file, "pub(crate) struct SkillFile {{")?;
    writeln!(
        file,
        "    /// Path of the file relative to its bundle root."
    )?;
    writeln!(file, "    pub(crate) relative_path: &'static str,")?;
    writeln!(
        file,
        "    /// File contents, exactly as embedded at build time."
    )?;
    writeln!(file, "    pub(crate) bytes: &'static [u8],")?;
    writeln!(file, "}}")?;
    writeln!(file)?;

    writeln!(file, "/// A skill bundle shipped inside the binary.")?;
    writeln!(file, "#[derive(Debug, Clone, Copy)]")?;
    writeln!(file, "pub(crate) struct SkillBundle {{")?;
    writeln!(
        file,
        "    /// Stable identifier for the bundle (matches its directory name)."
    )?;
    writeln!(file, "    pub(crate) id: &'static str,")?;
    writeln!(
        file,
        "    /// Files contained in this bundle, sorted by relative path."
    )?;
    writeln!(file, "    pub(crate) files: &'static [SkillFile],")?;
    writeln!(file, "}}")?;
    writeln!(file)?;

    writeln!(
        file,
        "/// All skill bundles shipped inside the binary, sorted by id."
    )?;
    writeln!(file, "pub(crate) static SKILL_BUNDLES: &[SkillBundle] = &[")?;
    for bundle in bundles {
        writeln!(file, "    SkillBundle {{")?;
        writeln!(file, "        id: {:?},", bundle.id)?;
        writeln!(file, "        files: &[")?;
        for (rel, bytes) in &bundle.files {
            writeln!(file, "            SkillFile {{")?;
            writeln!(file, "                relative_path: {rel:?},")?;
            write!(file, "                bytes: b\"")?;
            write_byte_literal(&mut file, bytes)?;
            writeln!(file, "\",")?;
            writeln!(file, "            }},")?;
        }
        writeln!(file, "        ],")?;
        writeln!(file, "    }},")?;
    }
    writeln!(file, "];")?;
    Ok(())
}

/// Write `bytes` as the body of a Rust byte-string literal (`b"..."`).
fn write_byte_literal<W: Write>(
    w: &mut W,
    bytes: &[u8],
) -> io::Result<()> {
    for &b in bytes {
        match b {
            b'"' => w.write_all(b"\\\"")?,
            b'\\' => w.write_all(b"\\\\")?,
            b'\n' => w.write_all(b"\\n")?,
            b'\r' => w.write_all(b"\\r")?,
            b'\t' => w.write_all(b"\\t")?,
            0 => w.write_all(b"\\0")?,
            0x20..=0x7E => w.write_all(std::slice::from_ref(&b))?,
            _ => write!(w, "\\x{b:02X}")?,
        }
    }
    Ok(())
}

/// Recursively collect regular files under a bundle directory while rejecting
/// symlinks, directories-only entries, and paths with `..` segments.
fn collect_files(
    root: &Path,
    current: &Path,
    out: &mut Vec<(String, Vec<u8>)>,
) -> io::Result<()> {
    let meta = fs::symlink_metadata(current)?;
    if meta.file_type().is_symlink() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("skill file must not be a symlink: {}", current.display()),
        ));
    }
    if meta.is_dir() {
        for entry in fs::read_dir(current)? {
            let entry = entry?;
            collect_files(root, &entry.path(), out)?;
        }
        return Ok(());
    }
    if !meta.is_file() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("unsupported file type: {}", current.display()),
        ));
    }
    let rel = current.strip_prefix(root).unwrap_or(current);
    reject_traversal_in_path(&rel.to_string_lossy()).map_err(|msg| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            format!("{msg} (path: {})", current.display()),
        )
    })?;

    let bytes = fs::read(current)?;
    out.push((rel.to_string_lossy().into_owned(), bytes));
    Ok(())
}

/// Reject path segments that would allow traversing outside the skills tree.
fn reject_traversal_in_path(path: &str) -> Result<(), String> {
    if Path::new(path).is_absolute() {
        return Err("skill paths must be relative".to_owned());
    }
    for component in Path::new(path).components() {
        if matches!(
            component,
            Component::ParentDir | Component::Prefix(_) | Component::RootDir
        ) {
            return Err("skill paths must not contain `..`, root, or prefix segments".to_owned());
        }
    }
    Ok(())
}
