[package]
name = "cbork"
version = "0.0.3"
edition.workspace = true
rust-version.workspace = true
license = "AGPL-3.0-only"
description = "Command-line tool for CDDL linting, validation, and effective CDDL rendering for CBOR schemas."
readme = "README.md"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
exclude = ["moon.yml"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
cbork-abnf-parser = { path = "../cbork-abnf-parser", version = "0.0.3" }
cbork-cddl-parser = { path = "../cbork-cddl-parser", version = "0.0.3" }
cbork-cddl-compiler = { path = "../cbork-cddl-compiler", version = "0.0.1" }
cbork-edn = { path = "../cbork-edn", version = "0.0.1" }
anyhow = "1.0"
console = "0.16.3"
bpaf = { version = "0.9.26", features = ["derive"] }
