# Copyright (c) 2026 Sakura Industries LLC.
#
# SPDX-License-Identifier: GPL-3.0-or-later

name = "CDDL"
grammar = "cddl"
path_suffixes = ["cddl"]
line_comments = [";"]
tab_size = 2
hard_tabs = false
